---
#
# Ansible managed
#
repository:
  description: Configure Logical Volumes Management (lvm), group and volumes.
  homepage: https://robertdebock.nl/
  topics: lvm, system, ansible, molecule, playbook
